package com.example.demo.Entity;


import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;


@Entity
@Table(name = "client")
public class Client {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "Client ID is autogenerated", hidden = true)
    private Long id;

    @Schema(description = "Name", example = "Juan", requiredMode = Schema.RequiredMode.REQUIRED)
    private String name;

    @Schema(description = "Lastname", example = "Perez", requiredMode = Schema.RequiredMode.REQUIRED)
    private String lastname;

    @Schema(description = "Document Number", example = "12345678", requiredMode = Schema.RequiredMode.REQUIRED)
    private String docNumber;

    public Client() {
    }

    public Client(Long id, String name, String lastname, String docNumber) {
        this.id = id;
        this.name = name;
        this.lastname = lastname;
        this.docNumber = docNumber;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getDocNumber() {
        return docNumber;
    }

    public void setDocNumber(String docNumber) {
        this.docNumber = docNumber;
    }
}
