package com.example.demo.Entity;


import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;

import java.util.Date;

@Entity
@Table(name = "invoice")
public class Invoice {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "Invoice ID is autogenerated", hidden = true)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "client_id")
    @Schema(description = "Client ID", requiredMode = Schema.RequiredMode.REQUIRED)
    private Client client;

    @Schema(hidden = true)
    private Date createdAt;


    @Schema(description = "Total invoice price", example = "1000.00", hidden = true)
    private Double total;

    public Invoice(Long id, Client client, Date createdAt, Double total) {
        this.id = id;
        this.client = client;
        this.createdAt = createdAt;
        this.total = total;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Double getTotal() {
        return total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }
}
