version: "3.3"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_USER=
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - MYSQL_DATA:/var/EntregaFinal/mysql

volumes:
  MYSQL_DATA: